version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
      - sudo chmod +x /usr/local/bin/ecs-cli
      - curl -L "https://github.com/docker/compose/releases/download/1.16.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
      - ecs-cli configure --cluster tutorial --region us-east-1 --default-launch-type FARGATE --config-name tutorial

      - $(aws ecr get-login --region us-east-1)
  build:
    commands:
      - docker-compose --version
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t httpd .
      - docker tag httpd:latest 417564495042.dkr.ecr.us-east-1.amazonaws.com/httpd:$CODEBUILD_SOURCE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 417564495042.dkr.ecr.us-east-1.amazonaws.com/httpd:$CODEBUILD_SOURCE_VERSION
      - ecs-cli compose --project-name tutorial service up
