version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t httpd .
      - docker tag httpd:55 417564495042.dkr.ecr.us-east-1.amazonaws.com/httpd:55
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 417564495042.dkr.ecr.us-east-1.amazonaws.com/httpd:55
