version: '2'
services:
  wordpress:
    image: 417564495042.dkr.ecr.us-east-1.amazonaws.com/httpd:$CODEBUILD_SOURCE_VERSION
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: tutorial
        awslogs-region: us-east-1
        awslogs-stream-prefix: wordpress
